SELECT * FROM customer;

# 1) What is the total revenue generated by male vs femlae customers?
SELECT SUM(purchase_amount) as total_revenue , gender
FROM customer 
GROUP BY gender ;

# 2) Which customer used a discount but still spent more than the average purchase amount?
SELECT customer_id , purchase_amount
FROM customer 
WHERE discount_applied = "Yes" AND 
	  purchase_amount >= ( SELECT AVG(purchase_amount) as average_purchase_amt
						  FROM customer ); 

# 3) Which are the top 5 products with the highest average review rating ? 
SELECT ROUND(AVG(review_rating),2) as rating_avg, item_purchased
FROM customer 
GROUP BY item_purchased
ORDER BY rating_avg DESC
LIMIT 5;

# 4) Compare the average purchase amounts between standard and express shipping
SELECT AVG(purchase_amount) as Average_Purchase_Amount , shipping_type
FROM customer 
WHERE shipping_type IN ("Express","Standard")
GROUP BY shipping_type ;

# 5) Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non subscribers
SELECT subscription_status, AVG(purchase_amount) as average_spend , SUM(purchase_amount) as total_revenue
FROM customer 
GROUP BY subscription_status;

# 6) Which 5 products have the highest percentage of purchases of discounts applied ? 
SELECT item_purchased , 100 * SUM(CASE WHEN discount_applied = "Yes" THEN 1 ELSE 0 END) / COUNT(*) AS discount_rate 
from customer 
group by item_purchased
order by discount_rate desc
limit 5;

# 7) Segment customers as New, Returning and Loyal based on their total number of previous purchases and shw the count of ecah segment 
WITH customer_segment as (
select 
CASE WHEN previous_purchases = 1 THEN "New" 
     WHEN previous_purchases BETWEEN 2 and 10 THEN "Returning"
     ELSE "Loyal"
END AS customer_type
FROM customer
)

SELECT customer_type, COUNT(customer_type) AS count
FROM customer_segment
GROUP BY customer_type;

# 8) What are the top 3 most purchased products within each category?
WITH item_counts as (
SELECT category, item_purchased, 
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC ) as item_rank
FROM customer 
GROUP BY category, item_purchased 
)

SELECT item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <= 3;

# 9) Are customers who are repeat-buyers (more than 5 previous purchases) also likely to subscribe?
WITH repeat_buyers1 as (
SELECT COUNT(customer_id) as cid1 
FROM customer
WHERE previous_purchases > 5 
	  AND subscription_status = "Yes"
),

repeat_buyers2 as (
SELECT COUNT(customer_id) as cid2
FROM customer
WHERE previous_purchases > 5 
	  AND subscription_status = "No"
)

select cid1,cid2
from repeat_buyers1, repeat_buyers2; 

# 10) What is the revenue contribution for each age group ?
SELECT SUM(purchase_amount) AS total_revenue, age_group 
FROM customer 
GROUP BY age_group
ORDER BY total_revenue DESC;

